INSERT INTO university(university_name,address,additional_info,website,region_id) VALUES 
("University of Bristol", "Bristol England","", "www.bristol.ac.uk","1"),
("University of Glasgow", "Glasgow Scotland", "","www.gla.ac.uk","1"), 
("University of Southampton", "Southampton England","","https://www.southampton.ac.uk/","1"), 
("University of Birmingham", "Birmingham England", "","www.birmingham.ac.uk","1"), 
("University of Leeds", "Leeds England", "","www.leeds.ac.uk/","1"), 
("Durham University", "Durham England", "","www.dur.ac.uk/","1"), 
("The University of Sheffield", "Sheffield England", "","www.sheffield.ac.uk/","1"), 
("University of Nottingham", "Nottingham England", "","www.nottingham.ac.uk/","1"), 
("Queen Mary University of London", "London England", "","www.qmul.ac.uk","1"), 
("Newcastle University", "Newcastle upon Tyne England", "","www.ncl.ac.uk","1"), 
("Lancaster University", "Lancaster England", "","www.lancaster.ac.uk/","1"), 
("University of Bath", "Bath England", "","https://www.bath.ac.uk/","1"), 
("University of Liverpool", "Liverpool England", "","www.liv.ac.uk","1"), 
("The University of Exeter", "Exeter England", "","www.exeter.ac.uk/","1"), 
("Cranfield University", "Cranfield England", "","www.cranfield.ac.uk","1"), 
("University of York", "York, England", "","www.york.ac.uk/","1"), 
("Cardiff University", "Cardiff, Wales", "","https://www.cardiff.ac.uk/","1"), 
("Queen`s University Belfast", "Belfast, Northern Ireland", "","www.qub.ac.uk","1"), 
("Loughborough University", "Loughborough & London, England", "","https://www.lboro.ac.uk/","1"), 
("University of Aberdeen", "Aberdeen, Scotland", "","www.abdn.ac.uk/","1"), 
("University of Sussex", "Brighton, England", "","https://www.sussex.ac.uk/","1"), 
("Heriot Watt University", "Edinburgh, Scotland", "","www.hw.ac.uk","1"), 
("University of Strathclyde", "Glasgow, Scotland", "","www.strath.ac.uk","1"), 
("University of Surrey ", "Guildford, England", "","www.surrey.ac.uk","1"), 
("University of Leicester", "Leicester, England", "","www.le.ac.uk","1"), 
("Swansea University", "Swansea, Wales", "","www.swansea.ac.uk","1"), 
("University of East Anglia", "Norwich, England", "","www.uea.ac.uk/","1"), 
("Brunel University of London", "London, England", "","www.brunel.ac.uk/","1"), 
("City, University of London", "London, England", "","https://www.city.ac.uk/","1"), 
("Oxford Brookes University", "Oxford, England", "","www.brookes.ac.uk","1"), 
("University of Dundee", "Dundee, Scotland", "","www.dundee.ac.uk","1"), 
("Aston University", "Birmingham, England", "","www.aston.ac.uk/","1"), 
("University of Stirling", "Stirling, Scotland", "","www.stir.ac.uk","1"), 
("University of Essex", "Colchester, England", "","www.essex.ac.uk/about/colchester/","1"), 
("Bangor University", "Bangor, Wales", "","www.bangor.ac.uk","1"), 
("Royal Holloway, University of London", "Egham, England", "","www.royalholloway.ac.uk/","1"), 
("The University of Huddersfield", "Huddersfield, England", "","www.hud.ac.uk","1"), 
("SOAS University of London", "London, England", "","https://www.soas.ac.uk/","1"), 
("University of Hull"," Hull, England", "","https://www.hull.ac.uk/","1"), 
("University of Hull"," London Campus, England", "","https://london.hull.ac.uk/","1"), 
("Coventry University", "Coventry & London, England", "","www.coventry.ac.uk","1"), 
("University of Bradford", "Bradford, England", "","www.bradford.ac.uk","1"), 
("Northumbria University", "Newcastle upon Tyne & London, England", "","www.northumbria.ac.uk","1"), 
("Nottingham Trent University"," Nottingham, England", "","www.ntu.ac.uk","1"), 
("Manchester Metropolitan University", "Manchester, England", "","www2.mmu.ac.uk","1"), 
("Kingston University", "Kingston, England", "","www.kingston.ac.uk","1"), 
("University of Portsmouth", "Portsmouth & London, England", "","www.port.ac.uk","1"), 
("University of Plymouth"," Plymouth, England", "","www.plymouth.ac.uk","1"), 
("Aberystwyth University", "Aberystwyth, Wales", "","https://aber.ac.uk/en/","1"), 
("Goldsmiths, University of London"," London, England", "","https://www.gold.ac.uk/","1"), 
("University of Greenwich"," London, England", "","www.gre.ac.uk","1"), 
("De MontFort University"," Leicester, England", "","www.dmu.ac.uk","1"), 
("Middlesex University"," London, England", "","www.mdx.ac.uk","1"), 
("University of the West of England", "Bristol, England", "","www.uwe.ac.uk/","1"), 
("Keele University"," Keele, England", "","www.keele.ac.uk/","1"), 
("University of Brighton"," Brighton, England", "","www.brighton.ac.uk/index.aspx","1"), 
("Edinburgh Napier University"," Edinburgh, Scotland", "","www.napier.ac.uk","1"), 
("London South Bank University"," London, England", "","www.lsbu.ac.uk","1"), 
("University of Hertfordshire"," Hatfield, England", "","www.herts.ac.uk","1"), 
("University of Lincoln"," Lincoln, England", "","https://www.lincoln.ac.uk/","1"), 
("University of East London"," London, England", "","www.uel.ac.uk","1"), 
("University of Salford"," Manchester, England", "","www.salford.ac.uk","1"), 
("Robert Gordon University"," Aberdeen, Scotland", "","https://www.rgu.ac.uk/","1"), 
("University of Central Lancashire"," Preston, England", "","www.uclan.ac.uk","1"), 
("London Metropolitan University"," London, England", "","https://www.londonmet.ac.uk/","1"), 
("Birmingham City University", "Birmingham, England", "","www.bcu.ac.uk","1"), 
("Sheffield Hallam University"," Sheffield, England", "","www.shu.ac.uk","1"), 
("The University of Northampton"," Northampton, England", "","www.northampton.ac.uk","1"), 
("Leeds Beckett University"," Leeds, England", "","www.leedsbeckett.ac.uk","1"), 
("University of Derby"," Derby, England", "","https://www.derby.ac.uk/","1"), 
("Canterbury Christ Church University"," Canterbury, England", "","https://www.canterbury.ac.uk/","1"), 
("University of Wolverhampton"," Wolverhampton, England", "","www.wlv.ac.uk","1"), 
("Anglia Ruskin University"," Cambridge & Chelmsford, England (Except Punjab and Haryana)", "","www.anglia.ac.uk/","1"), 
("Teesside University "," Middlesbrough and London Campus", "(Except Namakkal & Punjab)","www.tees.ac.uk","1"), 
("University of the West of Scotland", "Paisley, Scotland", "","www.uws.ac.uk","1"), 
("University of the West of Scotland"," London Campus, England", "","https://www.uwslondon.ac.uk/","1"), 
("University of South Wales "," Cardiff, Wales", "(Except Punjab & Haryana)","www.southwales.ac.uk","1"), 
("University of Roehampton"," London, England", "","www.roehampton.ac.uk","1"), 
("University of Staffordshire", "Stoke-on-Trent, England", "","www.staffs.ac.uk","1"), 
("University of Sunderland"," Sunderland & London, England", "","www.sunderland.ac.uk","1"), 
("University of Bedfordshire"," Luton, England", "","www.beds.ac.uk","1"), 
("Cardiff Metropolitan University", "Cardiff , Wales", "","www.cardiffmet.ac.uk","1"), 
("University of Chester, Chester", "England", "","www.chester.ac.uk","1"), 
("University of Gloucestershire"," Gloucester, England", "","www.glos.ac.uk/","1"), 
("University of West London"," London, England", "","www.uwl.ac.uk/","1"), 
("York St John University"," York, England", "","www.yorksj.ac.uk/","1"), 
("University of Bolton", "Bolton, England", "","https://www.bolton.ac.uk/","1"), 
("Abertay University"," Dundee, Scotland", "","https://www.abertay.ac.uk/","1"), 
("Liverpool Hope University"," Liverpool, England", "","www.hope.ac.uk","1"), 
("University of Wales Trinity Saint David"," London, Birmingham and Swansea Campus, England & Wales", "","https://www.uwtsd.ac.uk/","1"), 
("University of Chichester", "Chichester, England", "","https://www.chi.ac.uk/","1"), 
("St. Mary’s University"," Twickenham, England", "","https://www.stmarys.ac.uk/","1"), 
("Solent University"," Southampton, England", "","www.qahighereducation.com/solent-university-pathway","1"), 
("Leeds Trinity University"," Leeds, England", "","https://www.leedstrinity.ac.uk/","1"), 
("University for the Creative Arts", "Farnham, England", "","www.uca.ac.uk","1"), 
("Bishop Grosseteste University", "Lincoln, England", "","https://www.bgu.ac.uk/","1"), 
("BPP University (Except students from Andhra Pradesh", "Gujarat, Haryana, Jammu, Maharashtra, Punjab, UP, Uttarakhand, Tamil Nadu & Telangana), London, England", "","www.bpp.com","1"), 
("University of Law"," Guildford, England", "","https://www.law.ac.uk/","1"), 
("Ravensbourne University", "London, England", "","https://www.ravensbourne.ac.uk/","1"), 
("Leeds Arts University"," Leeds, England", "","https://www.leeds-art.ac.uk/","1"), 
("(Study Group) Bellerbys College", "Brighton, England", "","www.bellerbys.com","1"), 
("Norwich University of Arts", "Norwich, England", "","https://www.nua.ac.uk/","1"), 
("Regent’s University London"," London, England", "","www.regents.ac.uk","1"), 
("St George's University of London", "London, England", "","https://www.sgul.ac.uk/","1"), 
("University Academy 92"," Manchester, England", "","ua92.ac.uk/","1"), 
("University of Kent International College", "Canterbury, England", "","https://www.kent.ac.uk/international-college","1"), 
("Glion Institute of Higher Education"," London, England", "","https://www.glion.edu/","1"), 
("Regent College London, Middlesex"," England", "","https://www.rcl.ac.uk/","1"), 
("University of Hull (UG & PG Transfer Programs)"," Hull, England", "","www.oncampus.global/uk/campuses/oncampus-hull/welcome.htm","1"), 
("University College Birmingham"," Birmingham, England (Except Punjab and Haryana)", "","www.ucb.ac.uk/","1"), 
("Bloomsbury Institute"," London", "","https://www.bil.ac.uk/","1"), 
("Hult International Business School", "London, England", "","www.hult.edu","1"), 
("Cambridge School of Visual & Performing Arts (CSVPA)", "Cambridge, England", "","www.csvpa.com","1"), 
("Le - Cordon Bleu"," London, England", "","www.lcblondon.com","1"), 
("Istituto Marangoni"," London, England", "","www.istitutomarangoni.com/en/campuses/london","1"), 
("SP Jain London School of Management"," London, England", "","https://www.spjain.ac.uk/","1"), 
("The Engineering & Design Institute of London (TEDI-London)", "England", "","https://tedi-london.ac.uk/","1"), 
("University of Reading "," Reading, England", "(UG & PG Transfer Programs)","www.oncampus.global/uk/campuses/oncampus-reading/welcome.htm","1"), 
("Online Business School"," Conventry, England", "","https://www.onlinebusinessschool.com/","1"), 
("Birkbeck, University of London "," London, England", "(UG & PG Transfer Programs)","www.oncampus.global/uk/campuses/oncampus-london/birkbeck/about.htm","1"), 
("QAHE- Ulster University"," Birmingham, London & Manchester, England", "","www.qabs.ulster.ac.uk","1"), 
("(Study Group) Liverpool John Moores University"," Liverpool, England", "","www.ljmuisc.com","1"), 
("Royal Veterinary College, University of London "," London, England", "(UG Transfer Programs)","www.oncampus.global/uk/campuses/oncampus-london/royal-veterinary-college/about.htm","1"), 
("University of Alberta in Partnership with Kaplan", "Edmonton, Alberta ","(Only UG)","www.ualberta.ca/index.html","3"), 
("University of Waterloo", "Waterloo, Ontario","","uwaterloo.ca","3"), 
("Queen's University", "Kingston, Ontario"," (Only UG)","www.queensu.ca/","3"), 
("University of Calgary Continuing Education"," Calgary, Alberta","","https://conted.ucalgary.ca/","3"), 
("Dalhousie University", "Halifax, Nova Scotia","","www.dal.ca","3"), 
("University of Victoria in Partnership with Kaplan"," Victoria, British Columbia","","www.uvic.ca","3"), 
("York University, School of Continuing Education", "Toronto, Ontario","","www.yorku.ca","3"), 
("University of Guelph"," Guelph and Ridgetown Campus, Ontario","","www.uoguelph.ca","3"), 
("University of Windsor"," Windsor, Ontario","","www.uwindsor.ca","3"), 
("University of Manitoba", "Winnipeg, Manitoba","","www.umanitoba.ca","3"), 
("Memorial University of Newfoundland"," St. John's, Newfoundland and Labrador ","(Only PG)","www.mun.ca","3"), 
("Memorial University of Newfoundland", "Grenfell Campus, Newfoundland and Labrador ","(Only UG)","https://www.grenfell.mun.ca/Pages/home.aspx","3"), 
("University of New Brunswick"," Fredericton, New Brunswick","","www.unb.ca","3"), 
("University of New Brunswick", "Saint John, New Brunswick","(Except Students from India)","https://www.unb.ca/saintjohn/sjcollege/","3"), 
("Carleton University"," Ottawa, Ontario","","carleton.ca/","3"), 
("Toronto Metropolitan University"," Toronto, Ontario","","www.torontomu.ca/","3"), 
("University of Regina"," Regina, Saskatchewan","","www.uregina.ca","3"), 
("Brock University", "St. Catharines, Ontario","","www.brocku.ca","3"), 
("Wilfrid Laurier University", "Waterloo, Ontario","","www.wlu.ca","3"), 
("University of Lethbridge"," Lethbridge, Alberta ","(Only UG)","www.uleth.ca","3"), 
("Lakehead University", "Thunder Bay, Ontario","","www.lakeheadu.ca","3"), 
("Lakehead University through Georgian College"," Barrie, Ontario","","www.lakeheadgeorgian.ca","3"), 
("University of Winnipeg", "Winnipeg, Manitoba","","www.uwinnipeg.ca","3"), 
("University of Prince Edward Island", "Charlottetown, Prince Edward Island","","www.upei.ca","3"), 
("Acadia University", "Wolfville, Nova Scotia ","(Only UG)","www.acadiau.ca","3"), 
("St. Francis Xavier University", "Antigonish, Nova Scotia","","https://www.stfx.ca/","3"), 
("University of Northern British Columbia"," Prince George, British Columbia","","www.unbc.ca","3"), 
("Laurentian University"," Sudbury, Ontario (Except students from South Asia)","","https://laurentian.ca/","3"), 
("Thompson Rivers University"," Kamloops, British Columbia","","www.tru.ca","3"), 
("Ontario Tech University", "Oshawa, Ontario","","ontariotechu.ca/","3"), 
("Mount Saint Vincent University", "Halifax, Nova Scotia","","www.msvu.ca/en/home/default.aspx","3"), 
("Trent University, Peterborough"," Ontario","","www.trentu.ca","3"), 
("Trinity Western University"," Langley, British Columbia","","www.twu.ca","3"), 
("Royal Roads University, Victoria", "British Columbia","","www.royalroads.ca","3"), 
("Fairleigh Dickinson University"," Vancouver, British Columbia","","www.fdu.edu/vancouver","3"), 
("Simon Fraser University through Fraser International College", "Burnaby, British Columbia ","(Only UG)","www.sfu.ca","3"), 
("Wilfrid Laurier University through Wilfrid Laurier International College"," Brantford, Ontario ","(Only UG)","www.laurieric.ca/","3"), 
("University of Manitoba through International College of Manitoba, Winnipeg", "Manitoba ","(Only UG)","www.umanitoba.ca","3"), 
("University of Lethbridge through ULethbridge International College Calgary (UICC)", "Calgary, Alberta ","(Only UG)","https://www.uicc.ca/","3"), 
("Toronto Metropolitan University through Toronto Metropolitan International College"," Toronto, Ontario ","(Only UG)","www.ryersonuic.ca/","3"), 
("Vancouver Island University"," Nanaimo, British Columbia","","www.viu.ca","3"), 
("St. Thomas University", "Fredericton, New Brunswick (Only UG)","","www.stu.ca","3"), 
("University Canada West"," Vancouver, British Columbia","","www.ucanwest.ca","3"), 
("New York Institute of Technology", "Vancouver, British Columbia","","https://vancouver.nyit.edu/","3"), 
("Nipissing University", "North Bay, Ontario","","www.nipissingu.ca","3"), 
("Adler University, Vancouver"," British Columbia","","www.adler.edu/page/campuses/vancouver","3"), 
("King’s University College (University of Western Ontario)"," London, Ontario","","www.kings.uwo.ca","3"), 
("Cape Breton University", "Sydney, Nova Scotia","","www.cbu.ca","3"), 
("Capilano University", "North Vancouver, British Columbia","","www.capilanou.ca","3"), 
("Kwantlen Polytechnic University", "Surrey, British Columbia","","www.kpu.ca","3"), 
("University of the Fraser Valley", "Abbotsford, British Columbia","","www.ufv.ca","3"), 
("Mount Allison University"," Sackville, New Brunswick","","www.mta.ca","3"), 
("MacEwan University", "Edmonton, Alberta (Only UG)","","www.macewan.ca","3"), 
("University of Niagara Falls", "Niagara, Ontario","","https://unfc.com/","3"), 
("Crandall University"," Moncton and Sussex, New Brunswick","","https://www.crandallu.ca/","3"), 
("City University in Canada"," Calgary and Edmonton, Alberta ","(Master of Education in Leadership program only)","https://www.cityuniversity.ca/","3"), 
("Providence University College", "Winnipeg, Manitoba ","(Master of Management program only)","https://www.prov.ca/","3"), 
("Niagara University", "Vaughan, Ontario ","(Only PG)","https://niagarau.ca/","3"), 
("International Business University"," Toronto, Ontario ","(Except students from South Asia and Africa)","https://ibu.ca/","3"), 
("Algoma University", "Sault Ste. Marie, Ontario ","(Except students from South Asia)","https://algomau.ca/","3"), 
("Seneca Polytechnic", "Toronto, Ontario","","www.senecac.on.ca","3"), 
("Humber Polytechnic", "Toronto, Ontario","","https://www.humber.ca/","3"), 
("George Brown College", "Toronto, Ontario","","www.georgebrown.ca","3"), 
("Sheridan College", "Oakville, Ontario","","www.sheridancollege.ca","3"), 
("Bow Valley College", "Calgary, Alberta","","bowvalleycollege.ca/","3"), 
("St. Clair College of Applied Arts & Technology", "Windsor, Ontario","","https://www.stclaircollege.ca/","3"), 
("Douglas College"," New Westminster, British Columbia ","(Except students from Punjab, Haryana and Chandigarh)","www.douglascollege.ca","3"), 
("Southern Alberta Institute of Technology", "Calgary, Alberta","","www.sait.ca/","3"), 
("Northern Alberta Institute of Technology (NAIT), Edmonton","Alberta","","www.nait.ca","3"), 
("Niagara College"," Welland, Ontario","","www.niagaracollege.ca","3"), 
("Fanshawe College"," London, Ontario","","www.fanshawec.ca","3"), 
("Durham College", "Oshawa, Ontario","","www.durhamcollege.ca","3"), 
("Fleming College"," Peterborough, Ontario","","flemingcollege.ca/","3"), 
("North Island College"," Vancouver Island, British Columbia","","www.nic.bc.ca","3"), 
("Georgian College", "Barrie, Ontario","","www.georgianc.on.ca","3"), 
("Langara College, Vancouver", "British Columbia ","(Except students from Punjab and Haryana)","https://langara.ca/","3"), 
("Lakeland College"," Lloydminster and Vermilion, Alberta","","www.lakelandcollege.ca","3"), 
("Cambrian College, Sudbury"," Ontario","","www.cambriancollege.ca","3"), 
("Manitoba Institute of Trades and Technology"," Winnipeg, Manitoba","","www.mitt.ca","3"), 
("Conestoga College"," Kitchener, Ontario","","www.conestogac.on.ca","3"), 
("College of New Caledonia", "Prince George, British Columbia","","www.cnc.bc.ca","3"), 
("Saskatchewan Polytechnic", "Saskatoon, Saskatchewan","","www.saskpolytech.ca","3"), 
("LaSalle College"," Montreal and Vancouver","","www.lasallecollegevancouver.com","3"), 
("College of the Rockies"," Cranbrook, British Columbia","","www.cotr.bc.ca","3"), 
("Northern Lights College", "Dawson Creek, British Columbia","","www.nlc.bc.ca","3"), 
("Northern College", "Timmins, Ontario","","www.northernc.on.ca","3"), 
("Booth University College", "Winnipeg, Manitoba","","https://boothuc.ca/","3"), 
("St. Lawrence College", "Kingston, Ontario","","www.stlawrencecollege.ca","3"), 
("Lambton College", "Sarnia and Ottawa, Ontario","","www.lambtoncollege.ca","3"), 
("Selkirk College", "Castlegar, British Columbia","","www.selkirk.ca","3"), 
("Assiniboine College", "Brandon, Winnipeg and Dauphin Campus, Manitoba","","www.assiniboine.net","3"), 
("Keyano College", "Fort McMurray, Alberta","","https://www.keyano.ca/en/index.aspx","3"), 
("Canadore College", "North Bay, Ontario ","(Except students from Punjab and Haryana)","www.canadorecollege.ca","3"), 
("Acsenda School of Management", "Vancouver, British Columbia","","www.acsenda.com","3"), 
("Le Cordon Bleu", "Ottawa, Ontario","","www.lcbottawa.com","3"), 
("Alexander College", "Vancouver, British Columbia","","www.alexandercollege.ca","3"), 
("Vancouver Film School", "Vancouver, British Columbia","","www.vfs.edu","3"), 
("Vancouver Community College", "Vancouver, British Columbia","","www.vcc.ca","3"), 
("British Columbia Institute of Technology", "Burnaby, British Columbia","","www.bcit.ca","3"), 
("Medicine Hat College", "Medicine Hat, Alberta","","www.mhc.ab.ca","3"), 
("NorQuest College", "Edmonton, Alberta","","www.norquest.ca","3"), 
("Coquitlam College", "Coquitlam, British Columbia","","www.coquitlam.ca","3"), 
("Olds College, Olds", "Alberta","","https://www.oldscollege.ca/","3"), 
("Confederation College", "Thunder Bay, Ontario","","https://www.confederationcollege.ca/","3"), 
("Justice Institute of British Columbia"," New Westminster, British Columbia","","https://www.jibc.ca/","3"), 
("Great Plains College", "Swift Current, Saskatchewan","","https://www.greatplainscollege.ca/","3"), 
("North West College", "North Battleford, Saskatchewan","","https://www.northwestcollege.ca/","3"), 
("Suncrest College", "Yorkton, Saskatchewan","","https://parklandcollege.sk.ca/","3"), 
("Vancouver Premier College", "Vancouver, British Columbia","","https://vpcollege.com/","3"), 
("Oxford International College Halifax", "Halifax, Nova Scotia", "(CCA Program only)","https://oicolleges.com/halifax/","3"), 
("Oxford International College Vancouver", "Vancouver, British Columbia","","https://oicolleges.com/vancouver/","3"), 
("Trinity College Dublin", "Dublin","","www.tcd.ie","6"), 
("University College Dublin", "Dublin","","www.ucd.ie","6"), 
("University of Galway","Galway","","www.nuigalway.ie","6"), 
("University College Cork", "Cork","","www.ucc.ie","6"), 
("Dublin City University", "Dublin","","www.dcu.ie","6"), 
("University of Limerick", "Limerick","","www.ul.ie","6"), 
("Maynooth University", "Maynooth","","www.maynoothuniversity.ie","6"), 
("Technological University Dublin"," Dublin","","www.tudublin.ie","6"), 
("Munster Technological University", "","Cork and Kerry Campus","https://www.mtu.ie/","6"), 
("South East Technological University ","","(Waterford and Carlow Campus)","https://www.tuse.ie/","6"), 
("Atlantic Technological University ","","(Galway and Letterkenny Campus)","https://www.atu.ie/","6"), 
("Dundalk Institute of Technology"," Dundalk","","www.dkit.ie","6"), 
("Technological University of the Shannon: Midlands Midwest"," Shannon ","(Limerick and Athlone Campus)","https://tus.ie/","6"), 
("National College of Ireland"," Dublin","","www.ncirl.ie","6"), 
("Dublin Business School"," Dublin","","www.dbs.ie","6"), 
("Griffith College"," Dublin, Cork and Limerick (Campus in 3 cities)","","www.griffith.ie","6"), 
("Shannon College of Hotel Management"," A college of NUI Galway, Galway","","www.shannoncollege.com","6"), 
("Dublin International Foundation College", "Dublin","","https://www.difc.ie/","6"), 
("American College Dublin", "Dublin","","https://iamu.edu/","6"), 
("UniHaven College", "Maynooth","(On Campus)","https://www.oncampus.global/europe/campuses/oncampus-ireland/unihaven-college/about-unihaven-college.htm","6"), 
("IBAT College Dublin", "Dublin","","https://www.ibat.ie/","6"), 
("Independent College", "Dublin","","https://independentcollege.ie/","6"), 
("CCT College Dublin", "Dublin","","https://www.cct.ie/","6"), 
("University of Auckland", "Auckland","","https://www.auckland.ac.nz/en.html","7"), 
("University of Otago", "Dunedin","","https://www.otago.ac.nz/","7"), 
("Massey University"," Palmerston North","","www.massey.ac.nz/","7"), 
("Victoria University of Wellington", "Wellington","","www.victoria.ac.nz","7"), 
("University of Waikato", "Hamilton","","www.waikato.ac.nz","7"), 
("University of Canterbury", "Christchurch","","www.canterbury.ac.nz","7"), 
("Lincoln University", "Lincoln","","www.lincoln.ac.nz","7"), 
("Auckland University of Technology"," Auckland","","www.aut.ac.nz","7"), 
("Unitec Institute of Technology", "Auckland","","www.unitec.ac.nz","7"), 
("Otago Polytechnic", "Dunedin & Auckland","","www.otagopolytechnic.ac.nz","7"), 
("Manukau Institute of Technology - Te Pūkenga", "Auckland","","www.manukau.ac.nz","7"), 
("Ara Institute of Canterbury", "Christchurch","","www.ara.ac.nz","7"), 
("Eastern Institute of Technology", "Napier","","www.eit.ac.nz","7"), 
("Waikato Institute of Technology (Wintec)", "Hamilton","","https://www.wintec.ac.nz/","7"), 
("Nelson Marlborough Institute of Technology (NMIT)"," Nelson & Blenheim","","www.nmit.ac.nz","7"), 
("Whitireia New Zealand", "Porirua","","www.whitireia.ac.nz","7"), 
("Southern Institute of Technology", "Invercargill","","www.sit.ac.nz","7"), 
("Wellington Institute of Technology (WelTec)", "Wellington","","www.weltec.ac.nz","7"), 
("Western Institute of Technology at Taranaki (WITT)"," New Plymouth","","www.witt.ac.nz","7"), 
("North Tec", "Whangarei","","www.northtec.ac.nz","7"), 
("The Universal College of Learning (UCOL)", "almerston North","","https://www.ucol.ac.nz/","7"), 
("Toi Ohomai Institute of Technology", "Rotorua & Tauranga","","https://www.toiohomai.ac.nz/","7"), 
("New Zealand Skills and Education Group", "Auckland","","https://www.nzseg.com/","7"), 
("Pacific International Hotel Management School", "New Plymouth","","www.pihms.ac.nz","7"), 
("New Zealand Tertiary College (NZTC)", "Auckland","","https://www.nztertiarycollege.ac.nz/","7"), 
("Future Skills Academy","Auckland","","https://www.futureskills.co.nz","7"), 
("UC International College", "Christchurch","","www.ucic.ac.nz","7"), 
("Taylors College", "Auckland","","www.taylorscollege.edu.au","7"), 
("University of Waikato College", "Hamilton","","www.waikato.ac.nz","7"), 
("Whitecliffe College of Arts and Design", "Auckland & Christchurch","","www.whitecliffe.ac.nz","7"), 
("Whitecliffe College of Fashion and Sustainability", "Auckland & Wellington","","https://www.whitecliffe.ac.nz/fashion","7"), 
("Whitecliffe College of Technology & Innovation", "Auckland, Wellington & Christchurch","","https://www.whitecliffe.ac.nz/technology","7"), 
("Le Cordon Bleu", "Wellington","","www.cordonbleu.edu/new-zealand/welcome-to-new-zealand/en","7"), 
("New Zealand Airline Academy", "Oamaru","","www.nzaal.co.nz","7"), 
("AcademyEX Education", "Auckland","","https://academyex.com/","7"), 
("New Zealand Management Academies (NZMA)", "Auckland","","https://www.nzma.ac.nz/","7"), 
("The University of New South Wales"," Sydney ","(CRICOS Code 00098G)","www.unsw.edu.au","8"), 
("Monash University", "Melbourne ","(CRICOS Code 00008C)","www.monash.edu","8"), 
("The University of Queensland", "Brisbane )","(CRICOS Code 00025B","www.uq.edu.au/","8"), 
("University of Western Australia", "Perth ","(CRICOS Code: 00126G)","https://www.uwa.edu.au/","8"), 
("The University of Adelaide"," Adelaide ","(CRICOS Code 00123M)","www.adelaide.edu.au","8"), 
("University of Technology Sydney"," Sydney ","(CRICOS Provider No. 00099F, TEQSA: PRV12060)","international.uts.edu.au","8"), 
("RMIT University"," Melbourne ","(CRICOS Code 00122A)","www.rmit.edu.au","8"), 
("Macquarie University","Sydney ","(CRICOS Code 00002J)","www.mq.edu.au","8"), 
("University of Wollongong"," Wollongong ","(CRICOS Code 00102E)","https://www.uow.edu.au/","8"), 
("The University of Newcastle"," Newcastle ","(CRICOS Code 00109J)","www.newcastle.edu.au","8"), 
("University of Wollongong"," GIFT City Campus ","(CRICOS Code 00102E)","https://www.uow.edu.au/india/","8"), 
("Deakin University"," Melbourne, Geelong & Warrnambool Campus ","(CRICOS Code 00113B)","www.deakin.edu.au","8"), 
("Deakin University"," GIFT City Campus ","(CRICOS Code 00113B)","https://www.deakin.edu.au/gift-city-campus-india","8"), 
("Queensland University of Technology", "Brisbane ","(CRICOS Code 00213J)","www.qut.edu.au","8"), 
("La Trobe University", "Melbourne & Sydney ","(CRICOS Codes 00115M)","www.latrobe.edu.au/","8"), 
("Griffith University", "Gold Coast & Brisbane ","(CRICOS Code 00233E)","www.griffith.edu.au","8"), 
("Swinburne University of Technology", "Melbourne ","(CRICOS Code 00111D)","www.swinburne.edu.au","8"), 
("Swinburne University of Technology", "Sydney Campus ","(CRICOS Code 00111D)","https://www.swinburne.edu.au/sydney/","8"), 
("University of Tasmania", "Hobart, Launceston, Sydney ","(CRICOS Code 00586B)","www.utas.edu.au","8"), 
("University of Tasmania"," Melbourne ","(CRICOS Code 00586B)","https://www.utas.edu.au/community-and-partners/partner/educational/melbourne","8"), 
("Flinders University", "Adelaide ","(CRICOS Code 00114A)","www.flinders.edu.au","8"), 
("University of South Australia", "Adelaide ","(CRICOS Code 00121B)","www.unisa.edu.au","8"), 
("Western Sydney University","Sydney City Campus ","(CRICOS Code 00917K)","www.westernsydney.edu.au","8"), 
("Western Sydney University","","","https://www.westernsydney.edu.au/future/our-campuses/melbourne-campus","8"), 
("University of Canberra"," Sydney Hills ","(CRICOS Code 00212K)","https://eca.edu.au/","8"), 
("James Cook University", "Townsville, Cairns & Brisbane 011(CRICOS Code: 07J)","","www.jcu.edu.au/","8"), 
("CQUniversity Australia", "Sydney, Melbourne, Brisbane & Perth ","(CRICOS Code 00219C)","www.cqu.edu.au","8"), 
("Charles Darwin University"," Darwin ","(CRICOS Code 00300K)","https://www.cdu.edu.au/","8"), 
("Victoria University", "Brisbane Campus ","(CRICOS Code 02475D)","https://www.vu.edu.au/","8"), 
("Victoria University"," Sydney Campus ","(CRICOS Code 02475D)","https://eca.edu.au/","8"), 
("Charles Sturt University"," Wagga Wagga ","(CRICOS Code 00005F)","www.csu.edu.au","8"), 
("Charles Sturt University", "Sydney & Melbourne ","(CRICOS Code 00005F)","www.csu.edu.au","8"), 
("University of the Sunshine Coast", "Adelaide ","(CRICOS Code 01595D)","https://www.usc.edu.au/","8"), 
("The University of Notre Dame Australia", "Fremantle ","(CRICOS Code 01032F)","https://www.notredame.edu.au/","8"), 
("TasTAFE GETI", "Hobart, ","(CRICOS Code 03041M)","https://study.tas.gov.au/","8"), 
("S P Jain School of Global Management", "Sydney Campus ","(CRICOS Code 03335G)","https://www.spjain.org/global-campus/sydney","8"), 
("UNSW College", "Sydney (CRICOS Code 00098G)","","www.unswglobal.unsw.edu.au/","8"), 
("The University of Adelaide College", "", "(CRICOS Code 00123M)","college.adelaide.edu.au","8"), 
("UTS College", "Sydney","(CRICOS Codes UTS College 00859D, UTS 00099F)","utscollege.edu.au/","8"), 
("Charles Darwin University International College ", "", "(CRICOS Code 00300K)","www.cdu.edu.au/international/charles-darwin-university-international-college","8"), 
("Engineering Institute of Technology", "Perth, Melbourne and Brisbane ","(CRICOS Code 03567C)","www.eit.edu.au","8"), 
("ECA College of Health Sciences"," Brisbane & Sydney ","(CRICOS Code 03932J)","https://eca.edu.au/","8"), 
("Asia Pacific International College", "Sydney & Melbourne ","(CRICOS Code 03048D)","https://eca.edu.au/","8"), 
("Higher Education Leadership Institute", "Melbourne","(CRICOS Code 03845H)","https://eca.edu.au/","8"), 
("Le Cordon Bleu", "Adelaide, Sydney, Melbourne & Perth ","(CRICOS Code 02380M)","www.cordonbleu.edu/australia/home/en","8"), 
("Kaplan Business School", "Sydney","(CRICOS Code 02426B)(Only PG)","https://www.kbs.edu.au/","8"), 
("International College of Management", " Sydney","(CRICOS Code 01484M)","www.icms.edu.au","8"), 
("Academy of Interactive Technology", "Sydney", "215(CRICOS Code: 05J)","https://ait.edu.au/","8"), 
("Excelsia College", "Sydney ","(CRICOS Code 02664K)","https://excelsia.edu.au/","8"), 
("Ironwood Institute Adelaide", "Adelaide ","(CRICOS Code: 03039E)","https://ironwood.edu.au/","8"), 
("The Hotel School", "Sydney, Melbourne, Brisbane & Hayman Island ","(CRICOS Code 01241G)","https://hotelschool.scu.edu.au/","8"), 
("Australian College of Applied Professions", "Sydney ","(CRICOS Code 01328A)","www.acap.edu.au/","8"), 
("The University of Newcastle College of International Education", "Newcastle nte(CRICOS 00109J)","","irnationalcollege.newcastle.edu.au/contact.html","8"), 
("Curtin College", "Perth ","(CRICOS Code 02042G)","www.curtincollege.edu.au","8"), 
("Deakin College", "Melbourne ","(CRICOS Code 01590J)","www.deakincollege.edu.au","8"), 
("South Australia Institute of Business & Technology", "Adelaide ","(CRICOS Code 02193C)","www.saibt.sa.edu.au","8"), 
("Griffith College"," Gold Coast & Brisbane ","(CRICOS Code 01737F)","www.griffith.edu.au/college","8"), 
("La Trobe College", "Melbourne ","(CRICOS Code 03312D)","www.latrobecollegeaustralia.edu.au","8"), 
("Sydney Institute of Business & Technology", "Sydney ","(CRICOS code 01576G)","www.sibt.nsw.edu.au","8"), 
("Edith Cowan College ", "", "(CRICOS Code 01312J)","www.edithcowancollege.edu.au","8"), 
("Eynesbury College", "Adelaide ","(CRICOS Code 00561M)","www.eynesbury.navitas.com","8"), 
("University of Canberra College", "Canberra ","(CRICOS Code 00212K)","www.canberra.edu.au/uc-college","8"), 
("Russo Business School", "Brisbane 344(CRICOS Code – 01F)","","www.russo.qld.edu.au/","8"), 
("LaSalle College", "Melbourne ","(CRICOS Code 02201G)","www.lcimelbourne.edu.au/","8"), 
("Sarina Russo Institute", "Brisbane ","(CRICOS Code 00607B)","www.sri.edu.au","8"), 
("Analytics Institute of Australia", "Melbourne ","(CRICOS Code 04059D)","https://analyticsinstitute.edu.au/","8"), 
("Kent Institute Australia", "Sydney ","(CRICOS Code - 00161E)","https://kent.edu.au/","8"), 
("University of Connecticut"," Storrs Connecticut ","(Public Ivy) (OnlyUG)","uconn.edu/","2"), 
("Johns Hopkins Unlversity"," BaltImore Maryland ","(School of Engineering - Only PG)","httpx://wwwjhuedu/","2"), 
("Arlzona State Unlversity"," Phoenix Arizona","","www.nuLedu","2"), 
("University of Massachusetts Amherst"," Amherst Massachusetts ","(Masters Programe)","httpx://wwwmcas.adu/","2"), 
("University of Callfomia"," Riverside Callfornia ","(Graduate Business Programs & College of Engineering and UCR Extension)","business.ucr.edu/graduate","2"), 
("Virginia Tech Language and Culture Institute"," Blacksburg VirgInla ","(UG and PG Pathways)","wwwldl.t.edu","2"), 
("University of South Florida"," Tampa Florida"," (Only UG)","wwwunt.adu","2"), 
("University of Artzona"," Tucson Arizona","","www.araona.edu","2"), 
("Drexel University"," Fhiladelphin Pennsylvania ","(College of EngIneering UG Gateways and IEP)","www.drwowLecu","2"), 
("University of Delaware"," Newark Delaware ","(Only UG)","www.udeledu","2"), 
("Miaml University"," Oxford Ohlo ","(Public Ivy)","httpx://mlamlohuedal","2"), 
("University of Vermont"," Burlington Vermont ","(Only UG)","httpx://wwwarw.edu/","2"), 
("University of Wisconsin-Madison"," Madison Wsconsin"," (Pre College)","https://precollege.wisc.edu/international/","2"), 
("Lehigh Unlversity"," Bethlehem Fennsylvanla ","(Only PG)","https://www2.lehigh.edu/","2"), 
("Unlversity of Oregon"," Bugene Oregon","","https://uoregon.edu/","2"), 
("George Mason University"," Falrfax County VirgInla","","httpx:/wwwgruadu!","2"), 
("The University of Oklahama"," Norman Oklahoma","","https://www.ou.edu/","2"), 
("Colorado State University"," Fort Collins Colorado","","www.coloutate.edu","2"), 
("Oregon State University"," Corvallls Oregon","", "https://oregonstate.edu/","2"), 
("University of Ilinols at Chicaga"," Chicago Illinols ","(Only UG)","www.ulc.adu","2"), 
("The Unlversity of Alabama"," Tuscaloasa Alabama","","www.ua.ecky","2"), 
("Claremont Graduate University"," Claremont Callfornka","","www.cguedul","2"), 
("Auburn Unlversity"," Auburn Alnbama","","www.maburruedu","2"), 
("University of Utah"," Salt Lake Clty Utah ","(Only UG)","wwwutrhedu","2"), 
("University of Clncinnatl"," Clncinnati Ohlo","","www.uc.adu","2"), 
("Ohlo Unlversity","Athens, Ohlo","(Only UG)","httpa:/wwwahlo.eclu/","2"), 
("University of South Carolina","Columbla, South Carolina","","www.ac.edu","2"), 
("University of the Pacific","Stockton, Callfornlia","","www.pacihc.edu","2"), 
("University of Kansas"," Lawrence, Kansas ","(Only UG)","www.ku.edu","2"), 
("University of Tulsa","Tulsa, Oklahoma","","https://utulsa.edu/","2"), 
("Montclalr State Unlversity", "Montclalr, New Jersey","","httpa:/wwwmantclal.ecu/","2"), 
("University of Maryland", "BaltImore County, Maryland","","hittp:/urbc.adul","2"), 
("Univeraity of Tennessee at Chattanooga", "Chattanooga, Tennescee","","hittpa:/wwwtr.wdul","2"), 
("University at Albany", "The State Unlversity of New York at Albany ","(SUNY Albany)","https://www.albany.edu/","2"), 
("University of Dayton", "Dayton, Ohlo","","www.adayton.edu","2"), 
("University of Colorado Denver", "Denver, Colorado","","www.ucderwwradu","2"), 
("Southern Illinols University", "Carbondale, Ilinols","","http:/akuedul","2"), 
("University of Colorada", "Calorado Springs, Colarado","","www.uccudu","2"), 
("State University of New York at Geneseo (SUNY Genesea)", "Geneseo, New York","","www.prwawodu","2"), 
("SUNY Polytechnic Institute ", "Utica, New York","(SUNY Poly)","https://sunypoly.edu/","2"), 
("The State Unlversity of New York at New Paltz","","(SUNY New Paltz)","https://www.newpaltz.edu/","2"), 
("State University of New York at Fredonia ", "Fredonla, New York","(SUNY Fredonla)","www.fredonia.edu/","2"), 
("State Unlversity of New York at Plattsburgh "," Plattsburgh, New York","(SUNY Plattsburgh)","www.plattaburgh.adu","2"), 
("State Unlversity of New York College at Old Westbury" , "Old Westbury, New York","(SUNY Old Westbury)","https://www.oldwestbury.edu/","2"), 
("State Unlversity of New York at Oswego" ," Oswego, New York","(SUNY Oswego)","https://ww1.oswego.edu/","2"), 
("Queens College, Clty Unversity of New York","New York","","www.qc.cuny.edu","2"), 
("Cullnary Institute of America", "New York, Callfornia, and Texas Campus ","(Only UG)","http:/wwwclachetadu/","2"), 
("Loulslana State University", "Baton Rouge, Loulslana ","(Only UG)","wwwluLedu","2"), 
("Worcester Polytechnic Institute"," Worcester, Masoachusetts","","https://www.wpi.edu/","2"), 
("Washingto State University - Pullman", "Tri Citles, Everett, Vancouver, and Spokane Campus","","www.wauadu","2"), 
("University of Nebraska-Lincoln"," Lincoln Nebraska ","(Only UG)","www.unl.edu","2"), 
("University of Alabama at Birmingham"," Birmingham Alabama","","www.uab.edu","2"), 
("Virginia Commonwealth University"," Richmond Virginia","","https://www.vcu.edu/","2"), 
("Saint Louis University"," St. Louis Missouri","","www.slu.edu","2"), 
("Missouri University of Science and Technology"," Rolla Missouri","","www.mst.edu","2"), 
("University of Massachusetts Lowell"," Lowell Massachusetts","","www.uml.edu","2"), 
("Massachusetts College of Pharmacy and Health Sciences"," Boston Massachusetts (MCPHS University)","","www.mcphs.edu","2"), 
("University of Massachusetts"," Boston Massachusetts ","(UG PG Pathway and Direct Entry)","www.umb.edu","2"), 
("University of Massachusetts"," Dartmouth Massachusetts","","www.umassd.edu","2"), 
("Suffolk University"," Boston Massachusetts","","www.suffolk.edu","2"), 
("University of New Hampshire"," Durham New Hampshire","","www.unh.edu","2"), 
("Adelphi University"," New York- Garden City and Manhattan Campus","","www.adelphi.edu","2"), 
("University of Idaho"," Mosco Idaho","","www.uidaho.edu","2"), 
("San Jose State University"," San Jose California","","https://www.sjsu.edu/","2"), 
("San Francisco State University"," San Francisco California","","www.sfsu.edu/","2"), 
("California State University"," Los Angeles California","","https://www.calstatela.edu/","2"), 
("California State University"," Northridge California","","go.csun.edu/international","2"), 
("California State University"," Fresno California","","www.fresnostate.edu/","2"), 
("California State University"," East Bay California","","www.csueastbay.edu/","2"), 
("California State University"," Channel Islands California","","www.csuci.edu/","2"), 
("California State University"," Sacramento California","","https://www.csus.edu/","2"), 
("California State University"," Bakersfield California","","https://www.csub.edu/","2"), 
("California State University"," Dominguez Hills California","","www.csudh.edu/","2"), 
("California State University"," Stanislaus California","","https://www.csustan.edu/","2"), 
("California State University"," San Bernardino California","","https://www.csusb.edu/","2"), 
("Sonoma State University"," Rohnert Park California","","www.sonoma.edu/","2"), 
("California State Polytechnic University"," Pomona ","(College of the Extended University)","www.cpp.edu/index.shtml","2"), 
("University of California"," Irvine California ","(Division of Continuing Education)","https://ce.uci.edu/","2"), 
("University of California"," Berkeley Extension California","","https://extension.berkeley.edu/","2"), 
("University of California"," Santa Cruz Silicon Valley Extension (Professional Education)","","https://www.ucsc.edu/","2"), 
("Seattle University"," Seattle Washington","","www.seattleu.edu/","2"), 
("University of Central Florida"," Orlando Florida ","(Only PG)","https://www.ucf.edu/","2"), 
("New Jersey Institute of Technology"," Newark New Jersey","","www.njit.edu","2"), 
("Rochester Institute of Technology"," Rochester New York","","https://www.rit.edu/","2"), 
("Fairleigh Dickinson University"," Teaneck New Jersey","","www.fdu.edu/","2"), 
("Portland State University"," Portland, Oregon ","(Only UG)","https://www.pdx.edu/","2"), 
("Florida Institute of Technology"," Melbourne Florida","","www.fit.edu","2"), 
("Pace University"," Westchester & New York City Campus","","www.pace.edu","2"), 
("Drew University"," Madison New Jersey","","www.drew.edu","2"), 
("Lycoming College"," Williamsport Pennsylvania ","(Only UG)","https://www.lycoming.edu/","2"), 
("Whittier College"," Whittier California ","(Only UG)","https://whittier.edu/","2"), 
("Savannah College of Art and Design"," Savannah and Atlanta Campus Georgia","","www.scad.edu/","2"), 
("DePaul University"," Chicago Illinois","","www.depaul.edu","2"), 
("University of South Dakota"," Vermillion South Dakota","","https://www.usd.edu/","2"), 
("University of Hartford"," West Hartford Connecticut (Direct Entry and UG/PG Pathway)","","www.hartford.edu","2"), 
("Sacred Heart University"," Fairfield Connecticut","","www.sacredheart.edu/","2"), 
("Florida International University"," Miami Florida ","(All UG Programs) (PG Programs - Chapman Graduate School of Business)","www.fiu.edu","2"), 
("Kent State University"," Kent Ohio","","www.kent.edu","2"), 
("The University of Toledo"," Toledo Ohio ","(Only UG)","https://www.utoledo.edu/","2"), 
("University of Denver"," Colorado ","(Daniel’s College of Business only)","https://daniels.du.edu/","2"), 
("Nebraska Wesleyan Unlversity"," Lincoln Nebraska ","(Only UG)","www.nabrweslwyardu","2"), 
("Embry Riddle Aeronautical University"," Daytona Beach (Flarida) & Prescatt (Arizona) Campus","","https://erau.edu/","2"), 
("Mississippl State University"," Oktibbeha County Mississlppll","","www.msataie.edu","2"), 
("University of New Mexico"," Albuquerque New Mexico","","www.unm.edu","2"), 
("IlUnols State University"," Normal IWnols","","www.inoastatwedu","2"), 
("The Cathollc Unlversity of America"," Washington D.C.","","httpx:/wwwcathollc.eclu/nclw.html.","2"), 
("Oklahoma State University"," Stillwater Oklahoma ","(Only UG)","http://go.oatatmedul","2"), 
("Rowan Unlversity"," Glassboro New Jersey","","httpx:/wwwzowarvdul'","2"), 
("University of Wisconsin Milwaukee"," Milwaukee Wisconsin","","wwwuwimudu","2"), 
("Marquette Unlversity"," Milwaukee Wsconsin","","https://www.marquette.edu/","2"), 
("University of Nevada"," Reno Nevada","","wwwunr.adu","2"), 
("Ball State University"," Muncle Indana","","httpa:/wwwdbauachal","2"), 
("Cleveland State Unlversity"," Cleveland Ohlo","","www.csuohio.edu","2"), 
("Indlana Unlversity of Fennsylvanla"," Indiana PA","","www.lup.edu","2"), 
("Wright State Unlversity"," Dayton Ohlo","","www.wrightadu","2"), 
("Wichita State Unlversity"," Wichita Kansas","","www.wlchlta.edu","2"), 
("Northern Arizona University"," Flagstatf Arizona","","www.nauedu","2"), 
("University of North Texns"," Denton Texns","","www.unt.edu","2"), 
("University of North Texns at Frisco Texns","","","https://frisco.unt.edu/","2"), 
("University of Missourl"," St. Louls Missourl","","https://www.umsl.edu/","2"), 
("Middle Tennessee State University"," Murfreesboro Tennessee","","www.mtsu.edu/","2"), 
("University of Nebraska at Omaha"," Omaha Nebraska","","httpx:/wwwanomchcuedu/","2"), 
("The Unlversity of Memphis"," Memphis Tennessee","","www.memphla.edu","2"), 
("Tennessee Tech Unlversity"," Cookeville Tennessee","","www.tntech.adu","2"), 
("Texas State Unlversity"," San Marcos and Rock Round Campus Texas","","www.txstate.edu","2"), 
("University of North Florida"," Jacksonville Florida","","httpa:/wwwnf.adul","2"), 
("Florida Atlantic University"," Boca Raton Florida","","httpx://wwwfouadu/","2"), 
("Nova Southeastern Unlversity"," Davle Florida","","www.nova.edu","2"), 
("University of South Alabama"," Moblie Alabama","","www.southalnbama.adul","2"), 
("Montana State University"," Bozeman Montana","","www.montuna.edu","2"), 
("The University of Scranton"," Scranton Pennsylvanla","","www.acranton.edu!","2"), 
("Milwaukee School of Engineering"," Milwaukee Wisconaln","","www.msow.edu","2"), 
("Auburn University at Montgomery"," Montgomery Alabama","","www.muLedu","2"), 
("Hofstra Unlversity"," Long Island New York ","(UG, PG Pathway and Direct Entry)","www.hofatra.wdu","2"), 
("Kennesaw State University"," Kennesaw Georgla","","www.kennesaw.edu/","2"), 
("Roocevelt Unlversity"," Chicago and Schaumburg IlUnals","","http:/wwwrooowvelt.edul","2"), 
("Purdue Unlversity Northwest"," Hammond Indiana","","https://www.pnw.edu/","2"), 
("Long Island University"," Fost New York","","wwwlkdu/pcat","2"), 
("Long Island University"," Brooklyn New York","","wwwlluedu","2"), 
("Texas A &. M University"," Corpus Christi Texns","","https://www.tamucc.edu/","2"), 
("Western Kentucky Unlversity"," Bowling Green Kentucky","","www.wkLedu","2"), 
("Southeast Missourl State University"," Cape Glrardeau Missourl","","www.semo.edu","2"), 
("Youngstown State Unlversity"," Youngstown Ohlo","","www.yauedu","2"), 
("Callfornia Baptist University"," Riverside Callfornia","","www.colboptht.adu","2"), 
("Pacific Lutheran Unlversity"," Tacoma Washington","(Dlrect Entry and UG/PG Pathway)","www.pluedu","2"), 
("Arkansas State University"," Jonesbaro Arkansas","","wwwnstatwedu","2"), 
("University of Illinols Springheld"," Springheld Illinols","","httpx:/www.la.ech!","2"), 
("McMurry Unlversity"," Abllene Texns ","(Only UG)","https://mcm.edu/","2"), 
("Care Hope College"," Jupiter Florida ","(Only UG)","httpx:/wwwcarwhope.adu/","2"), 
("Lewis University"," Romeoville (illinois) and Albuquerque (New Mexico) Campus","","wwwdwwluudul","2"), 
("Governors State Unlversity"," Chicago IlUnols","","http:/wwwgowt.adul","2"), 
("Sauth Dakota School of Mines & Technology"," Rapld City South Dakota ","(Only UG)","https://www.sdsmt.edu/","2"), 
("Woodbury Unlversity"," Burbank Callfornia","","https://woodbury.edu/","2"), 
("Southern Illlnols University"," Edwardsville Illinols","","www.abn.edul","2"), 
("Western IWnols Unlversity"," Macomb and Quad Cities Campus IWnols","","www.wlu.edu!","2"), 
("University of New Haven"," West Haven Connectlcut","","www.nwwhavervedu","2"), 
("Dakota State Unlversity"," Madison South Dakotn","","www.dsu.edu","2"), 
("Pittsburg State Unlversity"," Pittsburg Kansas","","www.plttatotmedu","2"), 
("Missourl Southern State University"," Joplin Missourl","","httpx://wwwmasuadu/","2"), 
("University of Bridgeport"," Bridgeport Connecticut","","www.bridgeport.edu","2"), 
("Murrny State Unlversity"," Murray Kentucky","","https://www.murraystate.edu/","2"), 
("Marshall Unlversity Huntington"," Huntington West VirgInia","","https://www.marshall.edu/","2"), 
("Duquesne University"," Fittsburgh Pennaylvanla","","https://www.duq.edu/","2"), 
("Yeshiva University"," New York City","","https://potomac.edu/","2"), 
("Bryant Unliversity"," Smithheld Rhode Island ","(Only PG)","httpx:/wwwbryant.edu!","2"), 
("Southern Utnh Unlversity"," Cedar Utah","","httpx:/wwwauuadu!","2"), 
("Midwestern State University"," Wichita Falls Texns","","www.mwauadu","2"), 
("NY Tech"," New York (NYIT)","","www.nylt.wdu","2"), 
("Bay Atlantic University"," WashIngton D.C.","","https://bau.edu/","2"), 
("Roger Willlams Unlversity"," Bristol Rhode Island","","httpx://wwwrwuadu!","2"), 
("University Of Central Oklahoma"," Edmond Oklahoma","","www.uco.wdu","2"), 
("Central Methodist University"," Fayette Missourl","","http:/wwwcwntralmetodat.adu/","2"), 
("Central Michigan Unlversity"," Mount Pleasant Michigan","","www.cmlch.dlu!","2"), 
("University of the Potomac"," Washington DC and Virginia Campus","","httpx://potomac.adu/","2"), 
("University of LoulsvIlle"," Loulsville Kentucky","","http:Moulwvila.scku!","2"), 
("Eastern Michigan University"," Ypsllanti Michigan","","wwwamichadu/","2"), 
("Grand Valley State Unlversity"," Allendale Michigan","","www.gvsu.edu/","2"), 
("Lawrence Technological University"," Southfteld Michligan","","www.ltu.edu","2"), 
("University of Michigan-Flint"," Flint Michigan","","https://www.umflint.edu/","2"), 
("Texas A&M Unlversity - KingsvIlle"," Kingsville Texas","","httpx://wwwinmuk.eda/","2"), 
("University of Central Arkansas"," Conway Arkansas","","http:/ucrz.aclu/","2"), 
("Felician Unlversity"," Rutherford New Jersey","","https://felician.edu/","2"), 
("Salnt Leo University"," St. Leo Florida","","www.scintleo.adu","2"), 
("Midway University"," Midway Kentucky","","httpx://wwwmldwoy.edu!","2"), 
("University of North Carolina Wilmington"," Wilmington North Carolina","","http:/uncwcedu/","2"), 
("Johnson & Wales Unlversity"," Providence (Rhode Island) and Charlotte (North Carolina) Campus","","www.jww.edu","2"), 
("Northwest Missourl State University"," Maryville Missourl","","www.nwmlxxourLecu","2"), 
("South Unlversity"," Savannah, Geargla and Tampa Florida","","https://www.southuniversity.edu/","2"), 
("Missourl State University"," Springheld Missourl","","www.mlascuriatote.edu","2"), 
("Maryville University"," St. Louls Missourl","","http://wwwmaryvllmedu/","2"), 
("Callfornia Lutheran University"," Thousand Oaks Callfornia (Schoal of Management)","","https://www.callutheran.edu/","2"), 
("Salnt Mary College of Callfornia"," Moraga Callfarnlia","","httpx://wwwaimarys-cu.acu!","2"), 
("Weber State Unlversity"," Ogden Utah","","www.wwbr.edul","2"), 
("University of Tampa"," Tampa Flarida","","wwwut.edw","2"), 
("Xavier Untversity"," Cincinnat Ohlo","","http:/www.xavler.edu","2"), 
("Willlam Jessup Unlversity"," Rocklin & San Jose Campus Callfornia","","httpaxc/ijemaup.edul","2"), 
("Southern New Hampshire Unlversity"," Manchester New Hampchire","","www.anhu.edu","2"), 
("Troy Unlversity"," Troy Alnbama","","www.troyedu","2"), 
("Texas Wesleyan Unlversity"," Fort Worth Texas","","www.txwws.edu","2"), 
("Dallas Baptist Unlversity"," Dallas Texas","","httpx://wwwdbuadu/","2"), 
("Thomas Jefferson University"," Philadelphia Pennsylvania","","www.jffwraonadu","2"), 
("York College of Pennsylvania"," York Pennsylvania ","(Only UG)","httpx://wwwycpadu/","2"), 
("University of South Carolina Upstate"," Spartanburg South Carolina","","http://ucupatrte.acka/","2"), 
("University of St. Thomas"," Saint Paul Minnesota","","www.atthomas.edu!","2"), 
("Southwest Minnesota State University"," Marshall Minnesota","","www.amuedl","2"), 
("City University of Seattle"," Seattle WashIngton","","http://wwwzityuadu/","2"), 
("Western New England University"," Spring held Massachusetts","","www.wne.edu","2"), 
("River University"," Nashua New Hampshire","","www.rivler.edu","2"), 
("Northwood University"," Midland Michigan","","www.northwood.edu","2"), 
("Rider University"," Lawrence Township New Jersey","","www.rlder.ecu","2"), 
("Atlantis University"," Miami Florida","","https://atlantisuniversity.edu/","2"), 
("Valparaiso University"," Valparaiso Indiana","","wwwvalpa.adu","2"), 
("Trine University"," Angola Indiana","","www.trina.ecka!","2"), 
("Saginaw Valley State University"," Saginaw Michigan","","www.avaw.wdu","2"), 
("Slippery Rock University"," Slippery Rock Penneylvania","","www.aru.edu","2"), 
("Golden Gate University"," San Francisca California ","(Only PG)","www.pgu.edu","2"), 
("Westcliff University"," Irvine California","","www.wwatcl.achal","2"), 
("University of Wisconsin-Superior"," Superior Wisconsin ","(Only UG)","https://www.uwsuper.edu/","2"), 
("University of Wisconsin-Eau Clalre"," Eau Clalre and Barran County Campus Wisconsin","","https://www.uwec.edu/profiles/","2"), 
("University of Wisconsin-La Croase"," La Crosce Wisconsin","","www.wlax.wdu","2"), 
("University of Wisconsin-Stout", "Stout Wisconsin","","wwwuwatout.edu!","2"), 
("Western Oregon University"," Monmouth and Salem Oregon ","(Only UG)","http:/wou.edul","2"), 
("Charleston Southern University"," Charleston South CarolIna","","www.csunlcadu","2"), 
("Marymount Unlversity"," Arlington Virginia","","https://marymount.edu/","2"), 
("Devry University"," Downers Grove ILlinols","","www.devry.edu","2"), 
("East Carolina University"," Greenville North Carolina ","(Only UG)","www.ecu.acha!","2"), 
("James Madison University"," Harrisonburg Virginia ","(Only UG)","www.jmuedu","2"), 
("Tiffin University"," Tiffin Ohio","","www.tltfindal","2"), 
("Franklin University"," Columbus Ohio","","www.franklirdul","2"), 
("post University"," Waterbury Connecticut ","(Only UG)","httpx://paut.edu!","2"), 
("Academy of Art University"," San Francisco California","","www.ncademyart.adu","2"), 
("Full Sail University"," Winter Park Florida","","www.fullaalLedu","2"), 
("New York Film Academy"," New York City","","www.nyfa.wdu","2"), 
("Upper lowa Unlversity"," Fayette lowa","","wwwuledu","2"), 
("Oklahoma City University"," Oklahoma City Oklahoma","","www.okcuadu","2"), 
("Franklin College"," Franklin Indiana ","(Only UG)","http:/frankiincolegwedul","2"), 
("Webster University"," St. Louis (Missouri) and San Antonio (Texas) Campus","","https://webster.edu/","2"), 
("Truman State University"," Kirksville Missouri","","www.trumanedu/","2"), 
("Augustana University"," Sioux Falls South Dakota ","(Only UG)","www.mugle.edul","2"), 
("Park University"," Parkville (Missourl) and Gilbert (Arizona) Campus","","www.park.edu","2"), 
("The University of Findlay"," Findlay Ohio","","wwwhndlayuedu","2"), 
("Hult International Business School"," Boston & San Francisco campus","","wwwhult.edu","2"), 
("Simmons University"," Boston Massachusetts (Only UG women-focused)","","www.simmons.edu/","2"), 
("University of Mary Hardin-Baylor"," Belton Texas","","https://www.umhb.edu/","2"), 
("Lipscomb University"," Nashville Tennessee ","(Only UG)","wwwlipacombudu","2"), 
("Western Washington University"," Bellingham Washington","","www.wwwwdu","2"), 
("Miami University"," Hamilton & Middletown Campus Ohio ","(Only UG)","https://miamioh.edu/regionals/","2"), 
("New England Institute of Technology"," Warwick Rhode Island","","www.nalt.ecku","2"), 
("Marist College"," Poughkeepsie New York","","www.morlatedu","2"), 
("Spartan College of Aeronautics and Technology"," Tulsa Oklahoma ","(Only UG)","https://www.spartan.edu/","2"), 
("Ottawa University", "Ottawa Kansas", " campus(Only MBA-IT)","http:/wwwattawaadwbus/home","2"), 
("Mississippi College"," Clinton Mississippi","","www.mc.edu","2"), 
("Monroe College"," Bronx New York","","www.monroecollega.ecu","2"), 
("New England College"," Henniker New Hampshire","","www.nwc.eclu","2"), 
("Berkeley College"," New Jersey & New York","","http://berkelwycollagnadul","2"), 
("Richard Bland College of William & Mary"," Petersburg Virginia ","(Only UG)","https://www.rbc.edu/","2"), 
("Fisher College"," Boston Massachusetts","","www.fisher.edu","2"), 
("Santa Monica College"," Santa Monica California","","https://www.smc.edu/","2"), 
("Green River College"," Auburn Washington","","www.greenriver.edu","2"), 
("Seattle Colleges"," Seattle Washington","","www.seattlecentral.edu","2"), 
("San Mateo Colleges of Silicon Valley San Mateo"," California","(Cañada College, College of San Mateo, & Skyline College)","https://www.smccd.edu/international/","2"), 
("Santa Ana College"," Santa Ana California","","www.sac.edu","2"), 
("Santa Rosa Junior College"," Santa Rosa California","","www.santarosa.edu/","2"), 
("The Contra Costa Community College District"," Martinez California","","www.contracosta.edu/","2"), 
("Shoreline Community College"," Shoreline, Washington","","https://www.shoreline.edu/","2"), 
("Foothill De Anza Community College"," Los Altos Hills California","","https://www.fhda.edu/","2"), 
("Finger Lakes Community College Canandaigua"," New York","","https://www.flcc.edu/","2"), 
("Georgia State University"," Atlanta Georgia (ESL Programs only)","","www.gsu.edu/","2"), 
("Minnesota State University"," Mankato Minnesota (Center for English Language Programs)","","https://www.mnsu.edu/","2"), 
("Summer Discovery. Discovery Internship and Jr. Internship"," Roslyn, New York","","www.summerdiscovery.com","2"), 
("Lawrence Technological University (Michigan) and PIBM (Pune) Joint Degree Program (Global MBA)","", "","https://www.pibm.in/global-joint-degree-dual-program/admissions-2023.aspx","2"), 
("North Broward Preparatory School"," Florida","","https://www.nordangliaeducation.com/nbps-florida","2"), 
("Windermere Preparatory Boarding School"," Florida","","https://www.nordangliaeducation.com/wps-florida/boarding","2"), 
("The Village Boarding School"," Texas","","https://www.nordangliaeducation.com/village-houston","2"), 
("INSEEC Business School"," Paris","","https://www.inseec.com/en/","4"), 
("NEOMA Business School"," Rouen","","www.neoma-bs.com","4"), 
("ESCE International Business School"," Paris","","https://www.esce.fr/en/","4"), 
("ECE Engineering School"," Paris","","https://www.ece.fr/en/","4"), 
("(Navitas) ICN International College"," Paris","","https://www.icn-internationalcollege.com/","4"), 
("SupdePub School of Creation and Communication"," Paris","","https://www.supdepub.com/en/about-us/paris-campus/","4"), 
("HEIP, School of International and Political Studies"," Paris","","https://www.heip.fr/en/","4"), 
("Excelia Group"," La Rochelle","","www.excelia-group.com/?allow_language=true","4"), 
("ICN Business School"," Nancy","","https://www.icn-artem.com/en/","4"), 
("Kedge Business School"," Talence","","https://student.kedge.edu/","4"), 
("Montpellier Business School"," Montpellier","","https://www.montpellier-bs.com/international/","4"), 
("ESSCA School of Management"," Angers","","https://www.essca.fr/en/","4"), 
("EM Normandie Business School"," Paris","","www.ecole-management-normandie.fr/uk/","4"), 
("Clermont School of Business"," Clermont-Ferrand","","https://www.esc-clermont.fr/en/","4"), 
("Rennes School of Business"," Rennes","","www.rennes-sb.com","4"), 
("Skema Business School"," Paris","","www.skema.edu","4"), 
("Ecole Nationale Supérieure des Mines d'Alès - IMT Mines"," Alès (MSc in Disaster Management and Environmental Impact)","","www.mines-ales.fr/","4"), 
("Burgundy School of Business"," Dijon","","global.bsb-education.com/","4"), 
("Institut supérieur d`électronique de Paris (ISEP)"," Paris","","www.isep.org","4"), 
("EPITA - School of Engineering and Computer Science"," Paris","","www.epita.fr/en/","4"), 
("ESIGELEC"," Rouen","","www.esigelec.fr/en","4"), 
("Institut supérieur du commerce de Paris - ISC"," Paris","","www.iscparis.com","4"), 
("Le Cordon Bleu"," Paris","","www.lcbparis.com","4"), 
("De Vinci Higher Education"," Paris","","www.devinci.fr","4"), 
("College de Paris"," Paris","","www.collegedeparis.com","4"), 
("Queen Mary University of London"," Paris","","www.qmul.ac.uk/about/howtofindus/studyparis/","4"), 
("Instituto Marangoni Fashion and Design School"," Paris","","www.istitutomarangoni.com/en/campus/paris/","4"), 
("The American Business School of Paris"," Paris","","www.absparis.org/en/","4"), 
("Ecole Ducasse"," Paris","","www.ecoleducasse.com/en/campus-en/paris-campus","4"), 
("Berlin School of Business and Innovation"," Paris","","www.berlinsbi.com/international-student-guide/living-in-paris-france/the-campus-in-paris-france","4"), 
("IDRAC Business School"," Paris","","idrac-business-school.com/","4"), 
("ICD Business School"," Paris","","https://www.icd-bs.com/","4"), 
("Schiller International University"," Paris Campus","","https://schiller.edu/paris","4"), 
("École de Management Appliqué"," Paris","","https://www.ema.education/","4"), 
("Paris School of Business"," Paris","","https://www.psbedu.paris/en","4"), 
("ESDES School of Business and Management"," Lyon","","https://www.esdes.fr/","4"), 
("EPITECH"," Paris","","https://www.epitech.eu/","4"), 
("University of Antwerp"," Antwerp","","https://www.uantwerpen.be/en/","4"), 
("Thomas More, University of Applied Science, Antwerp","","","https://www.thomasmore.be/en/","4"), 
("Modul University, Vienna","","","www.modul.ac.at","4"), 
("International Business School (IBS)"," Vienna ","(Except students from Punjab & South India)","www.ibs-b.hu","4"), 
("Webster Vienna Private University", "Vienna","","https://www.webster.ac.at/","4"), 
("George Mason University"," Korea Campus","","https://masonkorea.gmu.edu/","5"), 
("University of Nottingham Ningbo China","china","","www.nottingham.edu.cn/en/index.aspx","5"), 
("United International College"," Zhuhai ","(Only UG)","https://www.uic.edu.cn/en/","5"), 
("RMIT University, Vietnam Campus","Vietnam","", "www.rmit.edu.vn/","5"), 
("International College of Liberal Arts"," Kofu","","https://www.icla.ygu.ac.jp/en/","5"), 
("Tokyo International University", "Kawagoe","","www.tiu.ac.jp/etrack/","5"), 
("Kudan Institute of Japanese language & Culture"," Tokyo","","www.kudan-japanese-school.com/","5"), 
("Middlesex University"," Mauritius Campus","","www.middlesex.mu","5"), 
("Monash University"," Malaysia Campus","","www.monash.edu.my/","5"), 
("University of Southampton"," Malaysia Campus","","https://www.southampton.ac.uk","5"), 
("University of Nottingham"," Malaysia Campus","","www.nottingham.edu.my/index.aspx","5"), 
("University of Wollongong"," Malaysia Campus","","https://www.uow.edu.my/","5"), 
("Heriot-Watt University"," Malaysia Campus","","www.hw.ac.uk/malaysia.htm","5"), 
("Taylor`s University"," Malaysia","","university.taylors.edu.my","5"), 
("Swinburne University","Malaysia Campus","","www.swinburne.edu.my","5"), 
("UCSI University", "Kuala Lumpur","","www.ucsiuniversity.edu.my/","5"), 
("Asia Pacific University of Technology And Innovation","Kuala Lumpur","","https://www.apu.edu.my/","5"), 
("University of Kuala Lumpur", "Malaysia","","www.unikl.edu.my/","5"), 
("Sunway Le Cordon Bleu"," Malaysia","","www.cordonbleu.edu/malaysia/home/en","5"), 
("Raffles University"," Malaysia Campus","","https://raffles-university.edu.my/","5"), 
("Raffles College of Higher Education"," Malaysia Campus","","https://raffles.edu.my/","5"), 
("MDIS Malaysia"," Gelang Patah","","https://www.mdis.edu.my/","5"), 
("University of Birmingham", "Dubai Campus","","www.birmingham.ac.uk/dubai/index.aspx","5"), 
("University of Wollongong"," Dubai Campus","","www.uowdubai.ac.ae","5"), 
("Curtin University"," Dubai Campus","","https://curtindubai.ac.ae/","5"), 
("Heriot Watt University"," Dubai Campus","","www.hw.ac.uk","5"), 
("University of Stirling"," Dubai Campus","","www.stir.ae/","5"), 
("Murdoch University"," Dubai Campus","","www.murdochdubai.ac.ae","5"), 
("Ajman University"," Ajman","","https://www.ajman.ac.ae/en","5"), 
("Canadian University", "Dubai","","www.cud.ac.ae","5"), 
("Abu Dhabi University"," Abu Dhabi & Dubai","","www.adu.ac.ae","5"), 
("Symbiosis International University"," Dubai Campus","","https://siu-dubai.ac.ae/","5"), 
("Middlesex University"," Dubai Campus","","www.mdx.ac.ae","5"), 
("De MontFort University"," Dubai Campus","","www.dmu.ac.uk/dubai/index.aspx","5"), 
("Birla Institute of Technology and Science (BITS Pilani)", "Dubai Campus","","https://www.bits-pilani.ac.in/Dubai/","5"), 
("Manipal Academy of Higher Education (MAHE)"," Dubai Campus","","www.manipal.edu/","5"), 
("Rochester Institute of Technology", "Dubai (RIT Dubai)","","www.rit.edu/dubai","5"), 
("Hult International Business School"," Dubai Campus","","www.hult.edu","5"), 
("S P Jain School of Global Management", "Dubai Campus","","https://www.spjain.org/global-campus/dubai","5"), 
("University of Bolton Academic Centre", "Ras Al Khaimah","","https://www.boltonac.ae/","5"), 
("EM Normandie"," Dubai Campus","","https://www.em-normandie.com/en/dubai-campus","5"), 
("HTMI Switzerland"," Dubai Campus","","www.htmidubai.com/","5"), 
("American University of Ras Al Khaimah","Ras Al Khaimah","","www.aurak.ac.ae/en/","5"), 
("The Emirates Academy of Hospitality Management"," Dubai","","www.emiratesacademy.edu","5"), 
("Synergy University", "Dubai Campus","","https://synergydubai.ae/","5"), 
("Emirates Aviation University"," Dubai","","www.eau.ac.ae","5"), 
("University of Europe for Applied Sciences"," Dubai","","https://www.ue-germany.com/about-us/locations/dubai","5"), 
("Istituto Marangoni Fashion and Design School"," Dubai","","https://www.istitutomarangoni.com/en/campus/dubai-school-of-fashion-and-design","5"), 
("Abu Dhabi Hospitality Academy - Les Roches"," Abu Dhabi Campus","","https://lesroches.edu/campuses/abu-dhabi/","5"), 
("Institute of Management Technology (IMT)"," Dubai","","www.imt.edu/imt-dubai/","5"), 
("Global Business Studies - GBS"," Dubai","","https://gbs.ac.ae/","5"), 
("UK College of Business and Computing"," Dubai Campus","","https://ukcbc.ac.ae/","5"), 
("Regent College"," Dubai Campus","","https://regenteducation.ae/","5"), 
("National University of Singapore ","singapore","(SCALE and ISS courses)","www.nus.edu.sg/","5"), 
("Technical University of Munich Asia ","singapore","(Only PG)","tum-asia.edu.sg/","5"), 
("Singapore University of Technology and Design (SUTD)","singapore","","https://www.sutd.edu.sg/","5"), 
("Curtin Singapore","singapore","","www.curtin.edu.sg","5"), 
("James Cook University (JCU)","singapore","","www.jcu.edu.au","5"), 
("Embry Riddle Aeronautical University Asia","singapore","","https://asia.erau.edu/","5"), 
("SIM Global Education","singapore","","www.simge.edu.sg","5"), 
("S P Jain School of Global Management","singapore","","www.spjain.org","5"), 
("Management Development Institute of Singapore (MDIS)","singapore","","www.mdis.edu.sg","5"), 
("PSB Academy","singapore","","www.psb-academy.edu.sg","5"), 
("Raffles College of Higher Education","singapore","","www.studyatraffles.com/singapore/","5"), 
("Kaplan Higher Education Academy (KHEA)","singapore","","www.kaplan.com.sg","5"), 
("William Angliss Institute","singapore","","www.angliss.edu.sg","5"), 
("Nanyang Institute of Management","singapore","","www.nanyang.edu.sg","5"), 
("East Asia Institute of Management","singapore","","https://www.eaim.edu.sg/en/","5");

UPDATE `university` SET `logo`= concat(university_id, '.png') WHERE 1;